name: Package and Deploy SAM Application

on:
  push:
    branches:
      - main
    paths:
      - 'template.yaml'
      - '**/*.py'
      - '**/**/*.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Adjust the version if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  deploy:
    name: Package and Deploy SAM Application using OIDC
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: SAM Package
        run: |
          sam package \
            --template-file template.yaml \
            --output-template-file packaged.yaml

      - name: SAM Deploy
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name cv-website \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --no-confirm-changeset \  # <-- This prevents the prompt
            --config-env default || [[ $? -eq 1 ]]
